"""empty message

Revision ID: cb733cbc27ba
Revises: 
Create Date: 2026-06-02 12:48:38.519879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb733cbc27ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('away_team_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('home_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('away_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(length=50), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_matches_api_id'), ['api_id'], unique=True)
        batch_op.drop_constraint('matches_team2_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('matches_team1_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teams', ['home_team_id'], ['id'])
        batch_op.create_foreign_key(None, 'teams', ['away_team_id'], ['id'])
        batch_op.drop_column('score2')
        batch_op.drop_column('team1_id')
        batch_op.drop_column('round')
        batch_op.drop_column('score1')
        batch_op.drop_column('team2_id')

    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goals_for', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goals_against', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_standings_api_id')
        batch_op.drop_column('goal_for')
        batch_op.drop_column('api_id')
        batch_op.drop_column('goal_against')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_id', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_index('ix_teams_code')
        batch_op.drop_index('ix_teams_name')
        batch_op.create_index(batch_op.f('ix_teams_api_id'), ['api_id'], unique=True)
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_teams_api_id'))
        batch_op.create_index('ix_teams_name', ['name'], unique=True)
        batch_op.create_index('ix_teams_code', ['code'], unique=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('api_id')

    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_against', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('api_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('goal_for', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_index('ix_standings_api_id', ['api_id'], unique=True)
        batch_op.drop_column('goals_against')
        batch_op.drop_column('goals_for')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team2_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score1', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('round', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('team1_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('score2', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('matches_team1_id_fkey', 'teams', ['team1_id'], ['id'])
        batch_op.create_foreign_key('matches_team2_id_fkey', 'teams', ['team2_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_matches_api_id'))
        batch_op.alter_column('match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.drop_column('stage')
        batch_op.drop_column('city')
        batch_op.drop_column('away_score')
        batch_op.drop_column('home_score')
        batch_op.drop_column('away_team_id')
        batch_op.drop_column('home_team_id')
        batch_op.drop_column('api_id')

    # ### end Alembic commands ###
